### ISSUE TITLE
Create -imx8 (and possibly -am62) variants of dotnet-uno container

### ISSUE THREAD

**Issue by charles2910** [toradex/torizon-containers#1]
Dotnet-uno use wayland-base as base. To have hw acceleration on imx8 and (possibly) am62, it needs access to our feeds (our upstream variant - rc only - doesn't have). So we should create variants based on wayland-base-imx8 and wayland-base-am62.

**Comment by andreriesco** [comment]
Since we are renaming things from the `-wayland` suffix to the `-imx8` and `-am62` suffixes for the `4` major, it makes sense now to replace the `dotnet-uno` container image with a more generic `dotnet-wayland` one that should be used for .NET GUI Frameworks in general. Therefore, replacing this issue with [this new one](https://github.com/toradex/torizon-containers/issues/2)

**Comment by andreriesco** [comment]
Since we are renaming things from the `-wayland` suffix to the `-imx8` and `-am62` suffixes for the `4` major, it makes sense now to replace the `dotnet-uno` container image with a more generic `dotnet-wayland` one that should be used for .NET GUI Frameworks in general. Therefore, replacing this issue with [this new one](https://github.com/toradex/torizon-containers/issues/2)
